config/routes.rb
Kickern::Application.routes.draw do

  resources :matches do
    resources :players
    resource :game
  end
  
  resources :player_sessions
  resources :players do 
    resources :matches
  end
  
  resources :games do
    resources :matches
  end
  
  resources :games do
    resources :matches
  end
  
  resources :teams

  match 'login' => 'player_sessions#new', :as => :login
  match 'logout' => 'player_sessions#destroy', :as => :logout
  
  

  root :to => "games#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/match.rb
class Match < ActiveRecord::Base
  
  module PlayerExtension
    def usernames
      proxy_target.collect(&:username).join(", ")
    end
  end
  
  validates_presence_of :yellow_goals
  validates_presence_of :white_goals
  
  
  GOALS_TO_WIN = [6,10]
  
  belongs_to :game
  has_many :teams, :dependent => :destroy do
    def create_colored_team(player_ids, color)
      player_ids.each do |player_id|
        proxy_association.owner.teams.create(
          :team_color => color,
          :player_id => player_id
        )
      end
    end
  end
  has_many :players, :through => :teams, :extend => PlayerExtension do
    def usernames
      proxy_target.collect(&:username).join(", ")
    end
  end
  
  has_many :white_players, 
    :through    => :teams, 
    :source     => :player, 
    :conditions => ["teams.team_color = ?", "white"],
    # :order => "id",
    :extend => PlayerExtension

  has_many :yellow_players, 
    :through    => :teams, 
    :source     => :player, 
    :conditions => ["teams.team_color = ?", "yellow"],
    # :order => "id",
    :extend => PlayerExtension
    
  default_scope :order => 'created_at DESC'

  def winner_players
    if self.white_goals < self.yellow_goals
       self.yellow_players
     else
       self.white_players
    end
  end
  
  def winner?(player)
    self.winner_players.include?(player)
  end
  
  def single?
    self.white_players.count == 1
  end

  def double?
    self.white_players.count == 2
  end
  
  def goals_shot_by_player(player)
    if white_players.include?(player)
      white_goals
    elsif yellow_players.include?(player)
      yellow_goals
    else 
      return nil
    end
  end
  
  def goals_sucked_by_player(player)
    if white_players.include?(player)
      yellow_goals
    elsif yellow_players.include?(player)
      white_goals
    else 
      return nil
    end
  end

  def check_for_creep_and_twitter_it
    if white_goals == 0
      TwitterClient.update("#{white_players.collect(&:username).join(" und ")} ist gekrochen. HAR HAR HAR")
    elsif yellow_goals == 0
      TwitterClient.update("#{yellow_players.collect(&:username).join(" und ")} ist gekrochen. HAR HAR HAR")
    end
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # acts_as_iphone_controller #:test_mode => true
  
  before_filter :load_match_and_game
  
  # GET /matches
  # GET /matches.xml
  def index
    if @game
      @matches = @game.matches
    else
      @matches = Match.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @matches }
      # format.iphone
    end
  end

  # GET /matches/1
  # GET /matches/1.xml
  def show
    @match = Match.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.xml
  def new
    
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @match }
      # format.iphone 
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.xml
  def create
    @match = @game.matches.create_match(params)
    
    respond_to do |format|
      if @match.valid?
        flash[:notice] = 'Match was successfully created.'
        if @game.finished?
          go_to = game_matches_path(@game)
        else
          go_to = new_game_match_path(@game)
        end
        format.html { redirect_to(go_to) }
        # format.iphone { redirect_to(go_to) }
        format.xml  { render :xml => @match, :status => :created, :location => @match }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
      end
      
      # format.iphone { @matches = Match.all; redirect_to :action => "index" }
    end
  end

  # PUT /matches/1
  # PUT /matches/1.xml
  def update
    # @match = @game.matches.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        flash[:notice] = 'Match was successfully updated.'
        format.html { redirect_to(@match) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.xml
  def destroy
    @match.destroy

    respond_to do |format|
      format.html { redirect_to(matches_url) }
      format.xml  { head :ok }
    end
  end
  
  private
    def load_match_and_game
      if params[:game_id]
        @game = Game.find(params[:game_id])
        @match = @game.matches.find(params[:id]) if params[:id]
      else
        @match = Match.find(params[:id]) if params[:id]
      end
    end
    
end

app/helpers/matches_helper.rb
module MatchesHelper
  
  def css_class_for_winner(match, color)
    if match.winner_players == match.send("#{color}_players")
      "winner"
    end
  end
  
  
  module ViewAttributes
    def caption
      yellow = "<span style=\"background-color: yellow\">#{yellow_players.collect(&:username).join(", ")}</span>"
      yellow_goals = "<span style=\"background-color: yellow\">#{self.yellow_goals}</span>"
      "#{yellow} vs. #{white_players.collect(&:username).join(", ")}: #{yellow_goals} zu #{self.white_goals}"
    end
  end
  
  def games_with_matches_list(games)
    te_grouped_list()
  end
  
  def matches_list(matches)
    view_matches = add_view_attributes(matches)
    # te_list(view_matches)
    te_grouped_list(view_matches.reverse){ |match| I18n.l(match.created_at.to_date, :format => :iphone) }
  end
  
  def add_view_attributes(matches)
    matches.each do |match|
      match.extend ViewAttributes
      match.send(:instance_eval, %Q{
        def url
          "#{match_path(match)}"
        end
      })
    end
  end
  
  
  
  
end

app/views/matches/_form.html.erb
<%- if @game -%>
  Eintragen der Ergebnisse vom <%= @game.matches.count + 1 %>. Match:
<%- end -%>

<%= render :partial => "shared/new_match_form" %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= form_for([@game, @match]) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :locals => {:f => f} %>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <tr>
    <th>White Team</th>
    <th>White Goals</th>
    <th>Yellow Goals</th>
    <th>Yellow Team</th>
    <th>Match date</th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td class="<%= css_class_for_winner(match, "white") %>"><%= show_names_of_players(match.white_players) %></td>
    <td><%= match.white_goals %></td>
    <td><%= match.yellow_goals %></td>
    <td class="<%= css_class_for_winner(match, "yellow") %>"><%= show_names_of_players(match.yellow_players) %></td>
    <td><%= link_to match.created_at.to_s(:short), match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', games_path %>

app/views/matches/index.iphone.erb
<span class="graytitle">Gewinner: <%= show_names_of_players(@game.winner_players) %></span>
<ul class="pageitem">
  <%- @matches.each do |match| %>
    <%- match_winner_player = (match.winner_players.blank? ? match.players.first : match.winner_players.first) -%>
    <li class="store match">
  	  <a href="<%= player_path(match_winner_player) %>">
        <span class="image" style="background-image: url('<%= match_winner_player.avatar.url(:thumb) %>');"></span>
        <span class="comment match_title">
          <span class="<%= css_class_for_winner(match, "white") %>">
            <%= show_names_of_players(match.white_players) %>
          </span> vs. 
          <span class="<%= css_class_for_winner(match, "yellow") %>">
             <%= show_names_of_players(match.yellow_players) %>
          </span>
        </span>
  	    <span class="name match_goals"><%= match.white_goals %> : <%= match.yellow_goals %></span>
        <!-- <img alt="rating" class="stars" src="images/4stars.png" /> -->
        <!-- <span class="starcomment">13 Reviews</span> -->
  	  </a>
  	</li>
  <%-end -%>
</ul>

app/views/matches/new.html.erb
<h1>Na, wer hat gewonnen?</h1>

<%= form_for([@game, @match]) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :locals => {:f => f} %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', matches_path %>

app/views/matches/new.iphone.erb
<%#= link_to "Save", "#", :type => "submit", :class=>"whiteButton" %>
<% form_for([@game, @match]) do |f| %>
  <%= f.error_messages %>

  <span class="graytitle">
    Weißer Spieler
  </span>
  <ul class="pageitem">
    <li class="form">
      <%= image_tag @game.matches.last.yellow_players.first.avatar.url(:small), :class => "player_image" %>
      <%= show_names_of_players @game.matches.last.yellow_players %>
      <%= hidden_field_tag("white_player_ids[]", @game.matches.last.yellow_player_ids)  %>
    </li>
    <li class="form">
      <%= select_tag(:white_goals, goals_select_options) %>
      <span class="arrow"></span>
    </li>
  </ul>

  <span class="graytitle yellow">
    Gelber Spieler 
  </span>
  <ul class="pageitem">
    <li class="form yellow">
      <%= image_tag @game.matches.last.white_players.first.avatar.url(:small), :class => "player_image" %>
      <span>
        <%= show_names_of_players @game.matches.last.white_players %>
      </span>
      <%= hidden_field_tag("yellow_player_ids[]", @game.matches.last.white_player_ids)  %>
    </li>
    <li class="form">
      <%= select_tag(:yellow_goals, goals_select_options) %>
      <span class="arrow"></span>
    </li>
  </ul>

  <ul class="pageitem">
  	<li class="form">
    <input name="Submit input" type="submit" value="Submit input" class="whiteButton" /></li>
  </ul>
<%- end -%>

app/views/matches/show.html.erb
<p>
  <b>White goals:</b>
  <%=h @match.white_goals %>
</p>

<p>
  <b>Yellow goals:</b>
  <%=h @match.yellow_goals %>
</p>

<p>
  <b>Goals to win:</b>
  <%=h @match.goals_to_win %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', game_matches_path(@match.game) %>

app/views/matches/show.iphone.erb
<p>
  <b>White player:</b>
  <%=h @match.white_player.usernames %>
</p>

<p>
  <b>Yellow player:</b>
  <%=h @match.yellow_team.usernames %>
</p>

<p>
  <b>White goals:</b>
  <%=h @match.white_goals %>
</p>

<p>
  <b>Yellow goals:</b>
  <%=h @match.yellow_goals %>
</p>

<p>
  <b>Goals to win:</b>
  <%=h @match.goals_to_win %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>