config/routes.rb
Kickern::Application.routes.draw do

  resources :matches do
    resources :players
    resource :game
  end
  
  resources :player_sessions
  resources :players do 
    resources :matches
  end
  
  resources :games do
    resources :matches
  end
  
  resources :games do
    resources :matches
  end
  
  resources :teams

  match 'login' => 'player_sessions#new', :as => :login
  match 'logout' => 'player_sessions#destroy', :as => :logout
  
  

  root :to => "games#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Kicker Statistiken der neuenZone</title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= javascript_include_tag 'jquery' %> 
  <%= yield(:script) %>
</head>
<body>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Kicker Statistiken der neuenZone</title>
<%= stylesheet_link_tag 'scaffold' %>
<!-- (en) Add your meta data here -->

<link href="/yaml/css/my_layout.css" rel="stylesheet" type="text/css"/>
<!--[if lte IE 7]>
<link href="/yaml/css/patches/patch_my_layout.css" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body>
<!-- skip link navigation -->
<ul id="skiplinks">
	<li><a class="skip" href="#nav">Skip to navigation (Press Enter).</a></li>
	<li><a class="skip" href="#col3">Skip to main content (Press Enter).</a></li>
</ul>

<div class="page_margins">
	<div class="page">
		<div id="header" role="banner">
			<div id="topnav" role="contentinfo">
				<span>
				  <%- if current_player -%>
				     <%= link_to "Edit profile", edit_player_path(:current) %> | <%= link_to "Logout", logout_path %>
				  <%- else -%>
				    <%= link_to "Login", login_path %> | <%= link_to "Register", new_player_path %>
				  <%- end -%>
				     | <a href="#">Contact</a> | <a href="#">Imprint</a></span> </div>
				<h1><%= h(yield(:title) || controller.action_name) %></h1>
				<span>A YAML based Layout in a <em>ready to use</em> project structure</span>
			</div>
		<!-- begin: main navigation #nav -->
		<div id="nav"  role="navigation">
			<div class="hlist">
				<ul>
				  <a href="<%= games_path %>">
					  <li class="active"><strong>Games</strong></li>
					</a>
          <li>
            <%= link_to "Players", players_path %>
          </li>
          <li>
            <%= link_to "Matches", matches_path %>
          </li>
          <li>
            <%= link_to "Teams", teams_path %>
          </li>
          <!-- <li><a href="#">Button 3</a></li>
          <li><a href="#">Button 4</a></li>
          <li><a href="#">Button 5</a></li> -->
				</ul>
			</div>
		</div>
		<!-- end: main navigation -->
		<!-- begin: main content area #main -->
		<div id="main">
		  <p style="color: green"><%= flash[:notice] %></p>

			<!-- begin: #col1 - first float column -->
			<div id="col1" role="complementary">
				<div id="col1_content" class="clearfix">
				  <ul>
				    <li><%= link_to 'New game', new_game_path %></li>
				  </ul>
          <!-- <h2>Column  #col1</h2>
          <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam malesuada   suscipit pede. Nullam ipsum lacus, varius vel, nonummy in, consequat ut, neque.   </p>
          <h3>Lorem ipsum ... </h3>
          <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam malesuada   suscipit pede. Nullam ipsum lacus, varius vel, nonummy in, consequat ut, neque.   Vivamus viverra. Duis dolor arcu, lacinia sit amet, sollicitudin sed, aliquet   vel, quam. Pellentesque molestie laoreet tortor. Aenean quam. Pellentesque magna   metus, venenatis sit amet, congue nec, dictum in, est. Aliquam nibh. </p> -->
				</div>
			</div>
			<!-- end: #col1 -->
			<!-- begin: #col3 static column -->
			<div id="col3" role="main">
				<div id="col3_content" class="clearfix">
					  <%= yield %>
				</div>
				<div id="ie_clearing">&nbsp;</div>
				<!-- End: IE Column Clearing -->
			</div>
			<!-- end: #col3 -->
		</div>
		<!-- end: #main -->
		<!-- begin: #footer -->
		<div id="footer" role="contentinfo">
			Footer with copyright notice and status information<br />
			Layout based on <a href="http://www.yaml.de/">YAML</a>
		</div>
		<!-- end: #footer -->
	</div>
</div>
<!-- full skip link functionality in webkit browsers -->
<script src="/yaml/yaml/core/js/webkit-focusfix.js" type="text/javascript"></script>
</body>
</html>

app/views/layouts/application.iphone.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>
    </title>
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
    <style>
        /* App custom styles */
    </style>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js">
    </script>
    <script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js">
    </script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_iui.iphone.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charjuqeset=UTF-8" />
  <title></title>
  <meta name = "viewport" content = "width = device-width, user-scalable=no 
      minimum-scale=1.0 maximum-scale=1.0"> 
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "iui" %>
  <%= include_tank_engine_files %>
  <%= stylesheet_link_tag "iphone" %>
  <%= yield :jquery %>
  <%= javascript_include_tag "tank_engine" %>
</head>
<body>
<div class="toolbar">
  <h1 id="pageTitle"><%= yield(:toolbar) or @title %></h1>
</div>

<%= yield %>
</body>
</html>